---
version: "3.6"
services:
  es_nginx:
    image: es_nginx
    build:
      context: ..
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 5000:80
    networks:
      - fpm
      - internet
    depends_on:
      - es_php_fpm

  es_php_fpm:
    image: es_php_fpm
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      MYSQL_HOST: es_database
      MYSQL_USER: engelsystem
      MYSQL_PASSWORD: engelsystem
      MYSQL_DATABASE: engelsystem

      # some optional env vars and their defaults can be seen here
      # for exact information have a look at config/config.default.php
      # MAINTENANCE: false
      # APP_NAME: "Engelsystem"
      # ENVIRONMENT:  'production'
      # APP_URL: null
      # FAQ_URL: 'https://events.ccc.de/congress/2013/wiki/Static:Volunteers'
      # MAIL_DRIVER: 'mail'
      # MAIL_FROM_ADDRESS: 'noreply@engelsystem.de'
      # MAIL_FROM_NAME: Engelsystem
      # MAIL_HOST: 'localhost'
      # MAIL_PORT: 587
      # THEME: 1
      # HOME_SITE: 'news'
      # DISPLAY_NEWS: 10
      # REGISTRATION_ENABLED: true
      # PASSWORD_MINIMUM_LENGTH: 8
      # REGISTRATION_ENABLE_DECT: true
      # REGISTRATION_ENABLE_USERNAME: false
      # REGISTRATION_ENABLE_DECT: false
      # REGISTRATION_ENABLE_PLANNED_ARRIVAL: true
      # REGISTRATION_ENABLE_TSHIRT: true
      # TIMEZONE: 'Europe/Berlin'
      # DEFAULT_LOCALE: 'en_US'
      # ADD_HEADERS: true
    networks:
      - database
      - fpm
      - internet
    depends_on:
      - es_database

  es_database:
    image: mariadb:10.2
    environment:
      MYSQL_DATABASE: engelsystem
      MYSQL_USER: engelsystem
      MYSQL_PASSWORD: engelsystem
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_INITDB_SKIP_TZINFO: "yes"
    volumes:
      - db:/var/lib/mysql
    networks:
      - database

volumes:
  db: {}

networks:
  database:
    internal: true
  fpm:
    internal: true
  internet:
